resolver: lts-8.5

packages:
- '.'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- hasql-pool-0.4.1

ghc-options:
  receive-order: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints